spring:
  application:
    name: sainsburys.applications.sc-is.location-supplier-acl
  cloud:
    stream:
      function:
        definition: sendTestData;concatFn
      bindings:
        #Test source binding (used for testing)
        sendTestData-out-0:
          destination: dataIn
          binder: kafka1
        concatFn-in-0:
          destination: dataIn
          binder: kafka3
          consumer:
            concurrency: 4
            useNativeDecoding: false
            spring.json.trusted.packages: 'multibinder'
            commit.interval.ms: 1000
        concatFn-out-0:
          destination: concatOut
          binder: kafka3
          producer:
            concurrency: 4
            useNativeDecoding: false
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${kafkaBroker2}
                      minPartitionCount: 4
                      configuration:
                        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
                        spring.json.value.default.type: multibinder.PriceSpecificationSource
                        commit.interval.ms: 1000
        kafka3:
          type: kstream
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        brokers: ${kafkaBroker2}
                        applicationId: multi-binder-kafka-streams
                        minPartitionCount: 4
                        configuration:
                          spring.json.trusted.packages: '*'
                          commit.interval.ms: 765
                          acks: all
                          max.poll.records: 1000
                          replication.factor: 1
                          allow.auto.create.topics: true
                          auto.register.schemas: true
                          auto.offset.reset: earliest
                          linger.ms: 300
                          default:
                            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                            value.serde: org.springframework.kafka.support.serializer.JsonSerde
                            consumer.enabledlq: true


